### PR TITLE
Include query parameters in serialization.

### PR DESCRIPTION
**Pull request by saga-dash**
Fix to pass query parameters to grpc server.
It may be necessary for Get method.

### CODE REVIEW

**Comment by konsumer** [comment]
This code should be doing that already:

```js
const convertParams = (req, url) => {
  const gparams = getParamsList(url)
  const out = req.body
  gparams.forEach(p => {
    if (req.query && req.query[p]) {
      out[p] = req.query[p]
    }
    if (req.params && req.params[p]) {
      out[p] = req.params[p]
    }
  })
  return out
}
```


 Does it not work?

**Comment by saga-dash** [comment]
oh,sorry
I should fix getParamsList.
[] is returned as a request like localhost:8080/get?id=1
The example above is not like REST :)

**Comment by konsumer** [comment]
I think maybe a fix to `getParamsList` would be better. I think my original intent was "just pull all the things out of query & params" but my code doesn't do that (the query stuff is inside a loop of params.) Totally a bug. I think I fixed this in some other code-base, but forgot to migrate it back to this repo.

I am thinking it might be best to do this, instead of `return out`:

```js
return Object.assign({}, req.query, req.params)
```

Since it's ok if there is extra stuff in there, and grpc does input param checking at the moment when it does the call to the handler, so you still get all the strengths of more rigid input-checking (it wont allow you to add arbitrary, not-in-proto-file query-params) we gain a lot and lose nothing.  I think actually that would kinda make the whole `convertParams` a bit pointless (call to it could be replaced simply with `{ ...req.query, ...req.params }`)

**Comment by saga-dash** [comment]
It certainly seems better to do it with req.params and req.query.
I will leave it to you whether to merge or rewrite.

**Comment by konsumer** [comment]
I think this is resolved in newer versions of grpc-dynamic-gateway, but if you continue to have issues, let me know, here.

**Pull request closed without merging**
